### ISSUE TITLE
[Feature Request] Laravel 11 Support

### ISSUE THREAD

**Issue by DellanX** [jeremy379/laravel-openid-connect#10]
Hi!

I'm looking to update to Laravel 11; however, this is one of the few packages that need some love to get there.
Ideally this is just a composer package update.

Is there anything I can do to help with this endeavor?
In the mean time I'll see if I can sandbox this library under Laravel 11, and hunt for any initial bugs.

**Comment by jeremy379** [comment]
Hey
I saw you submitted a PR, that's nice :) I merged it just now
