### ISSUE TITLE
Question about Keys

### ISSUE THREAD

**Issue by WendellAdriel** [jeremy379/laravel-openid-connect#8]
This package looks great, I'm going to create an OpenID implementation for an app and this is what I was looking for, I just have a quick question about the keys.

In Passport, I can set the keys as ENV variables:
https://laravel.com/docs/10.x/passport#loading-keys-from-the-environment

Does this package support this?

**Comment by jeremy379** [comment]
Hello

Thanks to [this contribution](https://github.com/jeremy379/laravel-openid-connect/pull/7) it should be supported :)

**Comment by WendellAdriel** [comment]
That's great, thank you so much! 🔥 💪
