### ISSUE TITLE
Discovery, JWKs and nounce support

### ISSUE THREAD

**Issue by moufmouf** [jeremy379/laravel-openid-connect#9]
Hey guys!

Given the fact this package is a fork of [ronvanderheijden/openid-connect](https://github.com/ronvanderheijden/openid-connect), I thought you might be interested to know I opened a few PRs in ronvanderheijden/openid-connect to add support for:

- Discovery document (https://github.com/ronvanderheijden/openid-connect/pull/16)
- JWKs (https://github.com/ronvanderheijden/openid-connect/pull/16)
- nounce support (https://github.com/ronvanderheijden/openid-connect/pull/17)

PRs are not merged yet but don't hesitate to get some inspiration / rebase them.

**Comment by amm834** [comment]
I assume a custom fork of the OpenID Connect will only work since the original owner is not working on it.

**Comment by aungmyatmoethegreat** [comment]
Can you provide your own fork?
